# Generated by Django 3.1.4 on 2020-12-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_topping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='text',
            new_name='name',
        ),
    ]
